---
title: "02_models"
author: "dima beaveroum"
date: "2026-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = TRUE)
```

## Data preprocessing

```{r}
library(tidyverse)

dataset_file <- file.path("Data", "health_quality_dataset.rds")
dataset <- readRDS(dataset_file)
dataset <- dataset %>% 
  filter(year > 2021) %>% 
  filter(age>14)

# 89 — код «не применимо / затрудняюсь ответить»: заменяем на NA в шкалах, которые входят в модели
scales_89 <- c("quality_state", "sat_health")

dataset %>%
  summarise(across(all_of(scales_89), \(x) sum(x == 89, na.rm = TRUE))) %>%
  pivot_longer(everything(), names_to = "Переменная", values_to = "Заменено 89 на NA") %>%
  knitr::kable()

dataset <- dataset %>%
  mutate(across(all_of(scales_89), \(x) na_if(x, 89L)))

```


```{r}
# Recode variables
dataset <- dataset %>% 
  mutate(unmet_ind = ifelse(unmet_reason_1 == 1 | unmet_reason_2 == 1, 1, 0), 
         unmet_fin = ifelse(unmet_reason_3 == 1 | unmet_reason_4 == 1, 1, 0), 
         unmet_org = ifelse(unmet_reason_5 == 1 | unmet_reason_6 == 1 | unmet_reason_8 == 1 | unmet_reason_9 == 1, 1, 0), 
         unmet_ter = ifelse(unmet_reason_7 == 1, 1, 0))

dataset <- dataset %>%
  mutate(edu = as.numeric(d008_UROV) + 1) %>% 
  mutate(edu = replace_values(edu, 8 ~ 1)) %>% 
  mutate(across(c(sex, edu, year, area, region_name), haven::as_factor))

dataset$edu <- factor(dataset$edu, levels = c("1", "2", "3", "4", "5", "6", "7"), labels = c( "нет", "дошкольное", "начальное", "основное среднее", "среднее / ТиПО", "высшее", "послевузовское"))
attributes(dataset$edu)$label <- "Образование: 1 нет, 2 дошкольное, 3 начальное, 4 основное среднее, 5 среднее / ТиПО, 6 высшее, 7 послевузовское"

```

```{r}
# Удаляем пропуски по всем переменным моделей m1–m7, чтобы все модели оценивались на одной
# выборке (иначе N различается и модели нельзя сравнивать).
model_vars <- c("quality_state", "sex", "age", "edu", "year", "area", "inc_eq_real_log",
                "sat_health", "unmet", "reg_doctors_per10k", "reg_health_exp_med_pc", "region_name")

n_before <- nrow(dataset)
dataset %>%
  summarise(across(all_of(model_vars), \(x) sum(is.na(x)))) %>%
  pivot_longer(everything(), names_to = "Переменная", values_to = "NA") %>%
  filter(`NA` > 0) %>%
  knitr::kable(caption = "Пропуски в переменных моделей")

dataset <- dataset %>% drop_na(all_of(model_vars))
cat("Удалено строк с NA:", n_before - nrow(dataset), "из", n_before,
    sprintf("(%.1f%%)", 100 * (n_before - nrow(dataset)) / n_before),
    "; осталось:", nrow(dataset), "\n")
```



```{r}
# Normalize Data
dataset_norm <- dataset %>%
  group_by(year) %>% 
  mutate_at(vars(quality_state, inc_eq_real_log, age, sat_health, reg_doctors_per10k, reg_health_exp_med_pc),  ~ scales::rescale(.) %>% as.vector) %>% 
  ungroup()

#head(dataset_norm, 5)  #check
```

## Modeling
### Socdem

```{r}
library(lme4)
m1 <- lmer(quality_state ~ sex + age + edu + year + area + inc_eq_real_log + (1 | region_name), data = dataset_norm)

#Sensitivity analysis for area type, as 3 out of 20 regions (Astana, Almaty, Shymkent) do not have rural area subgroup
dataset_sa <- dataset %>% 
  filter(region_name != c("г. Алматы", "г. Астана", "г. Шымкент"))
  
m1_sa <- lmer(quality_state ~ sex + age + edu + year + area + inc_eq_real_log + (1 | region_name), data = dataset_sa)
sjPlot::tab_model(m1, m1_sa, auto.label = F)
```

```{r}
m2 <- lmer(quality_state ~ sex + age + edu + year + area + inc_eq_real_log + sat_health + (1 | region_name), data = dataset_norm)
```

```{r}
sjPlot::tab_model(m1, m2, auto.label = F)
```

### Experience of Interactions

```{r}
m3 <- lmer(quality_state ~ sex + age + edu + year + area + inc_eq_real_log + sat_health +  as.factor(unmet) + (1 | region_name), data = dataset_norm)
sjPlot::tab_model(m3, auto.label = F)
```

```{r}
dataset_norm_exp <- dataset_norm %>% 
  filter(unmet == 1)

m4 <- lmer(quality_state ~ sex + age + edu + year + area + inc_eq_real_log + sat_health +  as.factor(unmet_ind) + as.factor(unmet_fin) + as.factor(unmet_org) + as.factor(unmet_ter) + (1 | region_name), data = dataset_norm_exp)
```

```{r}
sjPlot::tab_model(m3, m4, auto.label = F)
```


### Regional Differences

```{r}
m5 <- lmer(quality_state ~ sex + age + edu + year + area + inc_eq_real_log + sat_health + reg_health_exp_med_pc + (1 | region_name), data = dataset_norm)
```

```{r}
m6 <- lmer(quality_state ~ sex + age + edu + year + area + inc_eq_real_log + sat_health + reg_doctors_per10k + reg_health_exp_med_pc + (1 | region_name), data = dataset_norm)
```


```{r}
sjPlot::tab_model(m5, m6, auto.label = F)
performance::check_collinearity(m6)
```


### Interaction Effects

```{r}
m7 <- lmer(quality_state ~ sex + age + edu + year + area + sat_health + inc_eq_real_log * reg_doctors_per10k + (1 | region_name), data = dataset_norm)
```

```{r}
sjPlot::tab_model(m7, auto.label = F)
```

